#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  case "$(uname -s)" in
    Darwin)
      if ! git version 1>/dev/null 2>&1; then
        return 0
      fi
      ;;

  esac

  return 1
}

source sub "$BASH_SOURCE" "$@"
